import { Connection, Keypair, LAMPORTS_PER_SOL } from "@solana/web3.js";
import bs58 from "bs58";
import { appendFileSync, existsSync, readFileSync } from "node:fs";

async function main() {
  const envFile = "/app/.env";
  const existingEnv = existsSync(envFile) ? readFileSync(envFile, "utf8") : "";
  let secret: string;
  let kp: Keypair;
  const match = existingEnv.match(/^SERVER_WALLET_SECRET=(.+)$/m);
  if (match) {
    secret = match[1].trim();
    kp = Keypair.fromSecretKey(bs58.decode(secret));
    console.log(`[GACHA WALLET] Reusing existing wallet ${kp.publicKey.toBase58()}`);
  } else {
    kp = Keypair.generate();
    secret = bs58.encode(kp.secretKey);
    appendFileSync(envFile, `\n# Gacha MVP (devnet) — generated by scripts/gacha-init-wallet.ts\nSERVER_WALLET_SECRET=${secret}\nSOLANA_RPC_URL=https://api.devnet.solana.com\n`);
    console.log(`[GACHA WALLET] New wallet ${kp.publicKey.toBase58()}`);
    console.log(`[GACHA WALLET] Secret stored in ${envFile}`);
  }

  const rpc = process.env.SOLANA_RPC_URL || "https://api.devnet.solana.com";
  const conn = new Connection(rpc, "confirmed");
  const before = await conn.getBalance(kp.publicKey);
  console.log(`[GACHA WALLET] Current balance: ${(before / LAMPORTS_PER_SOL).toFixed(4)} SOL`);
  if (before >= 4 * LAMPORTS_PER_SOL) {
    console.log(`[GACHA WALLET] Balance sufficient, skipping airdrop`);
    return;
  }
  try {
    console.log(`[GACHA WALLET] Requesting airdrop of 2 SOL...`);
    const sig = await conn.requestAirdrop(kp.publicKey, 2 * LAMPORTS_PER_SOL);
    console.log(`[GACHA WALLET] Airdrop sig: ${sig}`);
    await conn.confirmTransaction(sig, "confirmed");
    const after = await conn.getBalance(kp.publicKey);
    console.log(`[GACHA WALLET] New balance: ${(after / LAMPORTS_PER_SOL).toFixed(4)} SOL`);
  } catch (err) {
    console.error(`[GACHA WALLET] Airdrop failed (rate-limited by faucet?):`, err instanceof Error ? err.message : err);
    console.error(`[GACHA WALLET] You can airdrop later with:`);
    console.error(`  solana airdrop 2 ${kp.publicKey.toBase58()} --url devnet`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
