/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/game'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifiedSalesRouteImport } from './routes/api.verified-sales'
import { Route as ApiVerifiedListedRouteImport } from './routes/api.verified-listed'
import { Route as ApiNftsRouteImport } from './routes/api.nfts'
import { Route as ApiNftListRouteImport } from './routes/api.nft-list'
import { Route as ApiMarketsRouteImport } from './routes/api.markets'
import { Route as ApiMarketSalesRouteImport } from './routes/api.market-sales'
import { Route as AppVerifiedSalesRouteImport } from './routes/_app.verified-sales'
import { Route as AppVerifiedListedRouteImport } from './routes/_app.verified-listed'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppNftListRouteImport } from './routes/_app.nft-list'
import { Route as AppGachaRouteImport } from './routes/_app.gacha'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppControlPanelRouteImport } from './routes/_app.control-panel'
import { Route as AppCollectionsRouteImport } from './routes/_app.collections'
import { Route as ApiIndexPokemonRouteImport } from './routes/api.index.pokemon'
import { Route as ApiVerifiedSalesLatestRouteImport } from './routes/api.verified-sales.latest'
import { Route as ApiScanNftMarketStatesRouteImport } from './routes/api.scan.nft-market-states'
import { Route as ApiSalesLatestRouteImport } from './routes/api.sales.latest'
import { Route as ApiRwaMarketStatsRouteImport } from './routes/api.rwa-market.stats'
import { Route as ApiRwaMarketListedRouteImport } from './routes/api.rwa-market.listed'
import { Route as ApiRwaMarketLatestSalesRouteImport } from './routes/api.rwa-market.latest-sales'
import { Route as ApiRwaMarketEventsRouteImport } from './routes/api.rwa-market.events'
import { Route as ApiRwaMarketEnrichSaleRouteImport } from './routes/api.rwa-market.enrich-sale'
import { Route as ApiRefreshVerifiedSalesRouteImport } from './routes/api.refresh.verified-sales'
import { Route as ApiRefreshNftDataRouteImport } from './routes/api.refresh.nft-data'
import { Route as ApiProvidersStatusRouteImport } from './routes/api.providers.status'
import { Route as ApiNftsUntrackRouteImport } from './routes/api.nfts.untrack'
import { Route as ApiNftsTrackedRouteImport } from './routes/api.nfts.tracked'
import { Route as ApiNftsTrackRouteImport } from './routes/api.nfts.track'
import { Route as ApiNftsStatusRouteImport } from './routes/api.nfts.status'
import { Route as ApiNftsRefreshRouteImport } from './routes/api.nfts.refresh'
import { Route as ApiNftsEnrichRouteImport } from './routes/api.nfts.enrich'
import { Route as ApiNftsAssetMintRouteImport } from './routes/api.nfts.$assetMint'
import { Route as ApiMarketsStateRouteImport } from './routes/api.markets.state'
import { Route as ApiHeliusKeysRouteImport } from './routes/api.helius.keys'
import { Route as ApiGachaOddsRouteImport } from './routes/api.gacha.odds'
import { Route as ApiGachaDrawRouteImport } from './routes/api.gacha.draw'
import { Route as ApiGachaDecideRouteImport } from './routes/api.gacha.decide'
import { Route as ApiGachaConfirmPaymentRouteImport } from './routes/api.gacha.confirm-payment'
import { Route as ApiGachaAdminRouteImport } from './routes/api.gacha.admin'
import { Route as ApiDiscoverNewMintsRouteImport } from './routes/api.discover.new-mints'
import { Route as AppCollectionsSlugRouteImport } from './routes/_app.collections.$slug'
import { Route as ApiIndexPokemonHistoryRouteImport } from './routes/api.index.pokemon.history'
import { Route as ApiWebhooksHeliusNftEventsRouteImport } from './routes/api.webhooks.helius.nft-events'
import { Route as ApiSalesProviderProviderRouteImport } from './routes/api.sales.provider.$provider'
import { Route as ApiSalesMarketMarketRouteImport } from './routes/api.sales.market.$market'
import { Route as ApiNftsCollectionsPreviewRouteImport } from './routes/api.nfts.collections.preview'
import { Route as ApiNftsCollectionsIngestRouteImport } from './routes/api.nfts.collections.ingest'
import { Route as ApiNftsCollectionsAllowedRouteImport } from './routes/api.nfts.collections.allowed'
import { Route as ApiNftsAssetMintMarketStateRouteImport } from './routes/api.nfts.$assetMint.market-state'
import { Route as ApiGachaStatusDrawIdRouteImport } from './routes/api.gacha.status.$drawId'

const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifiedSalesRoute = ApiVerifiedSalesRouteImport.update({
  id: '/api/verified-sales',
  path: '/api/verified-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifiedListedRoute = ApiVerifiedListedRouteImport.update({
  id: '/api/verified-listed',
  path: '/api/verified-listed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNftsRoute = ApiNftsRouteImport.update({
  id: '/api/nfts',
  path: '/api/nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNftListRoute = ApiNftListRouteImport.update({
  id: '/api/nft-list',
  path: '/api/nft-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketSalesRoute = ApiMarketSalesRouteImport.update({
  id: '/api/market-sales',
  path: '/api/market-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerifiedSalesRoute = AppVerifiedSalesRouteImport.update({
  id: '/verified-sales',
  path: '/verified-sales',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifiedListedRoute = AppVerifiedListedRouteImport.update({
  id: '/verified-listed',
  path: '/verified-listed',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppNftListRoute = AppNftListRouteImport.update({
  id: '/nft-list',
  path: '/nft-list',
  getParentRoute: () => AppRoute,
} as any)
const AppGachaRoute = AppGachaRouteImport.update({
  id: '/gacha',
  path: '/gacha',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppControlPanelRoute = AppControlPanelRouteImport.update({
  id: '/control-panel',
  path: '/control-panel',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const ApiIndexPokemonRoute = ApiIndexPokemonRouteImport.update({
  id: '/api/index/pokemon',
  path: '/api/index/pokemon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifiedSalesLatestRoute = ApiVerifiedSalesLatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => ApiVerifiedSalesRoute,
} as any)
const ApiScanNftMarketStatesRoute = ApiScanNftMarketStatesRouteImport.update({
  id: '/api/scan/nft-market-states',
  path: '/api/scan/nft-market-states',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalesLatestRoute = ApiSalesLatestRouteImport.update({
  id: '/api/sales/latest',
  path: '/api/sales/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRwaMarketStatsRoute = ApiRwaMarketStatsRouteImport.update({
  id: '/api/rwa-market/stats',
  path: '/api/rwa-market/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRwaMarketListedRoute = ApiRwaMarketListedRouteImport.update({
  id: '/api/rwa-market/listed',
  path: '/api/rwa-market/listed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRwaMarketLatestSalesRoute = ApiRwaMarketLatestSalesRouteImport.update({
  id: '/api/rwa-market/latest-sales',
  path: '/api/rwa-market/latest-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRwaMarketEventsRoute = ApiRwaMarketEventsRouteImport.update({
  id: '/api/rwa-market/events',
  path: '/api/rwa-market/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRwaMarketEnrichSaleRoute = ApiRwaMarketEnrichSaleRouteImport.update({
  id: '/api/rwa-market/enrich-sale',
  path: '/api/rwa-market/enrich-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefreshVerifiedSalesRoute = ApiRefreshVerifiedSalesRouteImport.update({
  id: '/api/refresh/verified-sales',
  path: '/api/refresh/verified-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefreshNftDataRoute = ApiRefreshNftDataRouteImport.update({
  id: '/api/refresh/nft-data',
  path: '/api/refresh/nft-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersStatusRoute = ApiProvidersStatusRouteImport.update({
  id: '/api/providers/status',
  path: '/api/providers/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNftsUntrackRoute = ApiNftsUntrackRouteImport.update({
  id: '/untrack',
  path: '/untrack',
  getParentRoute: () => ApiNftsRoute,
} as any)
const ApiNftsTrackedRoute = ApiNftsTrackedRouteImport.update({
  id: '/tracked',
  path: '/tracked',
  getParentRoute: () => ApiNftsRoute,
} as any)
const ApiNftsTrackRoute = ApiNftsTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => ApiNftsRoute,
} as any)
const ApiNftsStatusRoute = ApiNftsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiNftsRoute,
} as any)
const ApiNftsRefreshRoute = ApiNftsRefreshRouteImport.update({
  id: '/refresh',
  path: '/refresh',
  getParentRoute: () => ApiNftsRoute,
} as any)
const ApiNftsEnrichRoute = ApiNftsEnrichRouteImport.update({
  id: '/enrich',
  path: '/enrich',
  getParentRoute: () => ApiNftsRoute,
} as any)
const ApiNftsAssetMintRoute = ApiNftsAssetMintRouteImport.update({
  id: '/$assetMint',
  path: '/$assetMint',
  getParentRoute: () => ApiNftsRoute,
} as any)
const ApiMarketsStateRoute = ApiMarketsStateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => ApiMarketsRoute,
} as any)
const ApiHeliusKeysRoute = ApiHeliusKeysRouteImport.update({
  id: '/api/helius/keys',
  path: '/api/helius/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGachaOddsRoute = ApiGachaOddsRouteImport.update({
  id: '/api/gacha/odds',
  path: '/api/gacha/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGachaDrawRoute = ApiGachaDrawRouteImport.update({
  id: '/api/gacha/draw',
  path: '/api/gacha/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGachaDecideRoute = ApiGachaDecideRouteImport.update({
  id: '/api/gacha/decide',
  path: '/api/gacha/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGachaConfirmPaymentRoute = ApiGachaConfirmPaymentRouteImport.update({
  id: '/api/gacha/confirm-payment',
  path: '/api/gacha/confirm-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGachaAdminRoute = ApiGachaAdminRouteImport.update({
  id: '/api/gacha/admin',
  path: '/api/gacha/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoverNewMintsRoute = ApiDiscoverNewMintsRouteImport.update({
  id: '/api/discover/new-mints',
  path: '/api/discover/new-mints',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCollectionsSlugRoute = AppCollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppCollectionsRoute,
} as any)
const ApiIndexPokemonHistoryRoute = ApiIndexPokemonHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApiIndexPokemonRoute,
} as any)
const ApiWebhooksHeliusNftEventsRoute =
  ApiWebhooksHeliusNftEventsRouteImport.update({
    id: '/api/webhooks/helius/nft-events',
    path: '/api/webhooks/helius/nft-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSalesProviderProviderRoute =
  ApiSalesProviderProviderRouteImport.update({
    id: '/api/sales/provider/$provider',
    path: '/api/sales/provider/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSalesMarketMarketRoute = ApiSalesMarketMarketRouteImport.update({
  id: '/api/sales/market/$market',
  path: '/api/sales/market/$market',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNftsCollectionsPreviewRoute =
  ApiNftsCollectionsPreviewRouteImport.update({
    id: '/collections/preview',
    path: '/collections/preview',
    getParentRoute: () => ApiNftsRoute,
  } as any)
const ApiNftsCollectionsIngestRoute =
  ApiNftsCollectionsIngestRouteImport.update({
    id: '/collections/ingest',
    path: '/collections/ingest',
    getParentRoute: () => ApiNftsRoute,
  } as any)
const ApiNftsCollectionsAllowedRoute =
  ApiNftsCollectionsAllowedRouteImport.update({
    id: '/collections/allowed',
    path: '/collections/allowed',
    getParentRoute: () => ApiNftsRoute,
  } as any)
const ApiNftsAssetMintMarketStateRoute =
  ApiNftsAssetMintMarketStateRouteImport.update({
    id: '/market-state',
    path: '/market-state',
    getParentRoute: () => ApiNftsAssetMintRoute,
  } as any)
const ApiGachaStatusDrawIdRoute = ApiGachaStatusDrawIdRouteImport.update({
  id: '/api/gacha/status/$drawId',
  path: '/api/gacha/status/$drawId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/collections': typeof AppCollectionsRouteWithChildren
  '/control-panel': typeof AppControlPanelRoute
  '/dashboard': typeof AppDashboardRoute
  '/gacha': typeof AppGachaRoute
  '/nft-list': typeof AppNftListRoute
  '/sales': typeof AppSalesRoute
  '/verified-listed': typeof AppVerifiedListedRoute
  '/verified-sales': typeof AppVerifiedSalesRoute
  '/api/market-sales': typeof ApiMarketSalesRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/nft-list': typeof ApiNftListRoute
  '/api/nfts': typeof ApiNftsRouteWithChildren
  '/api/verified-listed': typeof ApiVerifiedListedRoute
  '/api/verified-sales': typeof ApiVerifiedSalesRouteWithChildren
  '/collections/$slug': typeof AppCollectionsSlugRoute
  '/api/discover/new-mints': typeof ApiDiscoverNewMintsRoute
  '/api/gacha/admin': typeof ApiGachaAdminRoute
  '/api/gacha/confirm-payment': typeof ApiGachaConfirmPaymentRoute
  '/api/gacha/decide': typeof ApiGachaDecideRoute
  '/api/gacha/draw': typeof ApiGachaDrawRoute
  '/api/gacha/odds': typeof ApiGachaOddsRoute
  '/api/helius/keys': typeof ApiHeliusKeysRoute
  '/api/markets/state': typeof ApiMarketsStateRoute
  '/api/nfts/$assetMint': typeof ApiNftsAssetMintRouteWithChildren
  '/api/nfts/enrich': typeof ApiNftsEnrichRoute
  '/api/nfts/refresh': typeof ApiNftsRefreshRoute
  '/api/nfts/status': typeof ApiNftsStatusRoute
  '/api/nfts/track': typeof ApiNftsTrackRoute
  '/api/nfts/tracked': typeof ApiNftsTrackedRoute
  '/api/nfts/untrack': typeof ApiNftsUntrackRoute
  '/api/providers/status': typeof ApiProvidersStatusRoute
  '/api/refresh/nft-data': typeof ApiRefreshNftDataRoute
  '/api/refresh/verified-sales': typeof ApiRefreshVerifiedSalesRoute
  '/api/rwa-market/enrich-sale': typeof ApiRwaMarketEnrichSaleRoute
  '/api/rwa-market/events': typeof ApiRwaMarketEventsRoute
  '/api/rwa-market/latest-sales': typeof ApiRwaMarketLatestSalesRoute
  '/api/rwa-market/listed': typeof ApiRwaMarketListedRoute
  '/api/rwa-market/stats': typeof ApiRwaMarketStatsRoute
  '/api/sales/latest': typeof ApiSalesLatestRoute
  '/api/scan/nft-market-states': typeof ApiScanNftMarketStatesRoute
  '/api/verified-sales/latest': typeof ApiVerifiedSalesLatestRoute
  '/api/index/pokemon': typeof ApiIndexPokemonRouteWithChildren
  '/api/gacha/status/$drawId': typeof ApiGachaStatusDrawIdRoute
  '/api/nfts/$assetMint/market-state': typeof ApiNftsAssetMintMarketStateRoute
  '/api/nfts/collections/allowed': typeof ApiNftsCollectionsAllowedRoute
  '/api/nfts/collections/ingest': typeof ApiNftsCollectionsIngestRoute
  '/api/nfts/collections/preview': typeof ApiNftsCollectionsPreviewRoute
  '/api/sales/market/$market': typeof ApiSalesMarketMarketRoute
  '/api/sales/provider/$provider': typeof ApiSalesProviderProviderRoute
  '/api/webhooks/helius/nft-events': typeof ApiWebhooksHeliusNftEventsRoute
  '/api/index/pokemon/history': typeof ApiIndexPokemonHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/collections': typeof AppCollectionsRouteWithChildren
  '/control-panel': typeof AppControlPanelRoute
  '/dashboard': typeof AppDashboardRoute
  '/gacha': typeof AppGachaRoute
  '/nft-list': typeof AppNftListRoute
  '/sales': typeof AppSalesRoute
  '/verified-listed': typeof AppVerifiedListedRoute
  '/verified-sales': typeof AppVerifiedSalesRoute
  '/api/market-sales': typeof ApiMarketSalesRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/nft-list': typeof ApiNftListRoute
  '/api/nfts': typeof ApiNftsRouteWithChildren
  '/api/verified-listed': typeof ApiVerifiedListedRoute
  '/api/verified-sales': typeof ApiVerifiedSalesRouteWithChildren
  '/collections/$slug': typeof AppCollectionsSlugRoute
  '/api/discover/new-mints': typeof ApiDiscoverNewMintsRoute
  '/api/gacha/admin': typeof ApiGachaAdminRoute
  '/api/gacha/confirm-payment': typeof ApiGachaConfirmPaymentRoute
  '/api/gacha/decide': typeof ApiGachaDecideRoute
  '/api/gacha/draw': typeof ApiGachaDrawRoute
  '/api/gacha/odds': typeof ApiGachaOddsRoute
  '/api/helius/keys': typeof ApiHeliusKeysRoute
  '/api/markets/state': typeof ApiMarketsStateRoute
  '/api/nfts/$assetMint': typeof ApiNftsAssetMintRouteWithChildren
  '/api/nfts/enrich': typeof ApiNftsEnrichRoute
  '/api/nfts/refresh': typeof ApiNftsRefreshRoute
  '/api/nfts/status': typeof ApiNftsStatusRoute
  '/api/nfts/track': typeof ApiNftsTrackRoute
  '/api/nfts/tracked': typeof ApiNftsTrackedRoute
  '/api/nfts/untrack': typeof ApiNftsUntrackRoute
  '/api/providers/status': typeof ApiProvidersStatusRoute
  '/api/refresh/nft-data': typeof ApiRefreshNftDataRoute
  '/api/refresh/verified-sales': typeof ApiRefreshVerifiedSalesRoute
  '/api/rwa-market/enrich-sale': typeof ApiRwaMarketEnrichSaleRoute
  '/api/rwa-market/events': typeof ApiRwaMarketEventsRoute
  '/api/rwa-market/latest-sales': typeof ApiRwaMarketLatestSalesRoute
  '/api/rwa-market/listed': typeof ApiRwaMarketListedRoute
  '/api/rwa-market/stats': typeof ApiRwaMarketStatsRoute
  '/api/sales/latest': typeof ApiSalesLatestRoute
  '/api/scan/nft-market-states': typeof ApiScanNftMarketStatesRoute
  '/api/verified-sales/latest': typeof ApiVerifiedSalesLatestRoute
  '/api/index/pokemon': typeof ApiIndexPokemonRouteWithChildren
  '/api/gacha/status/$drawId': typeof ApiGachaStatusDrawIdRoute
  '/api/nfts/$assetMint/market-state': typeof ApiNftsAssetMintMarketStateRoute
  '/api/nfts/collections/allowed': typeof ApiNftsCollectionsAllowedRoute
  '/api/nfts/collections/ingest': typeof ApiNftsCollectionsIngestRoute
  '/api/nfts/collections/preview': typeof ApiNftsCollectionsPreviewRoute
  '/api/sales/market/$market': typeof ApiSalesMarketMarketRoute
  '/api/sales/provider/$provider': typeof ApiSalesProviderProviderRoute
  '/api/webhooks/helius/nft-events': typeof ApiWebhooksHeliusNftEventsRoute
  '/api/index/pokemon/history': typeof ApiIndexPokemonHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/game': typeof GameRoute
  '/_app/collections': typeof AppCollectionsRouteWithChildren
  '/_app/control-panel': typeof AppControlPanelRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gacha': typeof AppGachaRoute
  '/_app/nft-list': typeof AppNftListRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/verified-listed': typeof AppVerifiedListedRoute
  '/_app/verified-sales': typeof AppVerifiedSalesRoute
  '/api/market-sales': typeof ApiMarketSalesRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/nft-list': typeof ApiNftListRoute
  '/api/nfts': typeof ApiNftsRouteWithChildren
  '/api/verified-listed': typeof ApiVerifiedListedRoute
  '/api/verified-sales': typeof ApiVerifiedSalesRouteWithChildren
  '/_app/collections/$slug': typeof AppCollectionsSlugRoute
  '/api/discover/new-mints': typeof ApiDiscoverNewMintsRoute
  '/api/gacha/admin': typeof ApiGachaAdminRoute
  '/api/gacha/confirm-payment': typeof ApiGachaConfirmPaymentRoute
  '/api/gacha/decide': typeof ApiGachaDecideRoute
  '/api/gacha/draw': typeof ApiGachaDrawRoute
  '/api/gacha/odds': typeof ApiGachaOddsRoute
  '/api/helius/keys': typeof ApiHeliusKeysRoute
  '/api/markets/state': typeof ApiMarketsStateRoute
  '/api/nfts/$assetMint': typeof ApiNftsAssetMintRouteWithChildren
  '/api/nfts/enrich': typeof ApiNftsEnrichRoute
  '/api/nfts/refresh': typeof ApiNftsRefreshRoute
  '/api/nfts/status': typeof ApiNftsStatusRoute
  '/api/nfts/track': typeof ApiNftsTrackRoute
  '/api/nfts/tracked': typeof ApiNftsTrackedRoute
  '/api/nfts/untrack': typeof ApiNftsUntrackRoute
  '/api/providers/status': typeof ApiProvidersStatusRoute
  '/api/refresh/nft-data': typeof ApiRefreshNftDataRoute
  '/api/refresh/verified-sales': typeof ApiRefreshVerifiedSalesRoute
  '/api/rwa-market/enrich-sale': typeof ApiRwaMarketEnrichSaleRoute
  '/api/rwa-market/events': typeof ApiRwaMarketEventsRoute
  '/api/rwa-market/latest-sales': typeof ApiRwaMarketLatestSalesRoute
  '/api/rwa-market/listed': typeof ApiRwaMarketListedRoute
  '/api/rwa-market/stats': typeof ApiRwaMarketStatsRoute
  '/api/sales/latest': typeof ApiSalesLatestRoute
  '/api/scan/nft-market-states': typeof ApiScanNftMarketStatesRoute
  '/api/verified-sales/latest': typeof ApiVerifiedSalesLatestRoute
  '/api/index/pokemon': typeof ApiIndexPokemonRouteWithChildren
  '/api/gacha/status/$drawId': typeof ApiGachaStatusDrawIdRoute
  '/api/nfts/$assetMint/market-state': typeof ApiNftsAssetMintMarketStateRoute
  '/api/nfts/collections/allowed': typeof ApiNftsCollectionsAllowedRoute
  '/api/nfts/collections/ingest': typeof ApiNftsCollectionsIngestRoute
  '/api/nfts/collections/preview': typeof ApiNftsCollectionsPreviewRoute
  '/api/sales/market/$market': typeof ApiSalesMarketMarketRoute
  '/api/sales/provider/$provider': typeof ApiSalesProviderProviderRoute
  '/api/webhooks/helius/nft-events': typeof ApiWebhooksHeliusNftEventsRoute
  '/api/index/pokemon/history': typeof ApiIndexPokemonHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/collections'
    | '/control-panel'
    | '/dashboard'
    | '/gacha'
    | '/nft-list'
    | '/sales'
    | '/verified-listed'
    | '/verified-sales'
    | '/api/market-sales'
    | '/api/markets'
    | '/api/nft-list'
    | '/api/nfts'
    | '/api/verified-listed'
    | '/api/verified-sales'
    | '/collections/$slug'
    | '/api/discover/new-mints'
    | '/api/gacha/admin'
    | '/api/gacha/confirm-payment'
    | '/api/gacha/decide'
    | '/api/gacha/draw'
    | '/api/gacha/odds'
    | '/api/helius/keys'
    | '/api/markets/state'
    | '/api/nfts/$assetMint'
    | '/api/nfts/enrich'
    | '/api/nfts/refresh'
    | '/api/nfts/status'
    | '/api/nfts/track'
    | '/api/nfts/tracked'
    | '/api/nfts/untrack'
    | '/api/providers/status'
    | '/api/refresh/nft-data'
    | '/api/refresh/verified-sales'
    | '/api/rwa-market/enrich-sale'
    | '/api/rwa-market/events'
    | '/api/rwa-market/latest-sales'
    | '/api/rwa-market/listed'
    | '/api/rwa-market/stats'
    | '/api/sales/latest'
    | '/api/scan/nft-market-states'
    | '/api/verified-sales/latest'
    | '/api/index/pokemon'
    | '/api/gacha/status/$drawId'
    | '/api/nfts/$assetMint/market-state'
    | '/api/nfts/collections/allowed'
    | '/api/nfts/collections/ingest'
    | '/api/nfts/collections/preview'
    | '/api/sales/market/$market'
    | '/api/sales/provider/$provider'
    | '/api/webhooks/helius/nft-events'
    | '/api/index/pokemon/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/collections'
    | '/control-panel'
    | '/dashboard'
    | '/gacha'
    | '/nft-list'
    | '/sales'
    | '/verified-listed'
    | '/verified-sales'
    | '/api/market-sales'
    | '/api/markets'
    | '/api/nft-list'
    | '/api/nfts'
    | '/api/verified-listed'
    | '/api/verified-sales'
    | '/collections/$slug'
    | '/api/discover/new-mints'
    | '/api/gacha/admin'
    | '/api/gacha/confirm-payment'
    | '/api/gacha/decide'
    | '/api/gacha/draw'
    | '/api/gacha/odds'
    | '/api/helius/keys'
    | '/api/markets/state'
    | '/api/nfts/$assetMint'
    | '/api/nfts/enrich'
    | '/api/nfts/refresh'
    | '/api/nfts/status'
    | '/api/nfts/track'
    | '/api/nfts/tracked'
    | '/api/nfts/untrack'
    | '/api/providers/status'
    | '/api/refresh/nft-data'
    | '/api/refresh/verified-sales'
    | '/api/rwa-market/enrich-sale'
    | '/api/rwa-market/events'
    | '/api/rwa-market/latest-sales'
    | '/api/rwa-market/listed'
    | '/api/rwa-market/stats'
    | '/api/sales/latest'
    | '/api/scan/nft-market-states'
    | '/api/verified-sales/latest'
    | '/api/index/pokemon'
    | '/api/gacha/status/$drawId'
    | '/api/nfts/$assetMint/market-state'
    | '/api/nfts/collections/allowed'
    | '/api/nfts/collections/ingest'
    | '/api/nfts/collections/preview'
    | '/api/sales/market/$market'
    | '/api/sales/provider/$provider'
    | '/api/webhooks/helius/nft-events'
    | '/api/index/pokemon/history'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/game'
    | '/_app/collections'
    | '/_app/control-panel'
    | '/_app/dashboard'
    | '/_app/gacha'
    | '/_app/nft-list'
    | '/_app/sales'
    | '/_app/verified-listed'
    | '/_app/verified-sales'
    | '/api/market-sales'
    | '/api/markets'
    | '/api/nft-list'
    | '/api/nfts'
    | '/api/verified-listed'
    | '/api/verified-sales'
    | '/_app/collections/$slug'
    | '/api/discover/new-mints'
    | '/api/gacha/admin'
    | '/api/gacha/confirm-payment'
    | '/api/gacha/decide'
    | '/api/gacha/draw'
    | '/api/gacha/odds'
    | '/api/helius/keys'
    | '/api/markets/state'
    | '/api/nfts/$assetMint'
    | '/api/nfts/enrich'
    | '/api/nfts/refresh'
    | '/api/nfts/status'
    | '/api/nfts/track'
    | '/api/nfts/tracked'
    | '/api/nfts/untrack'
    | '/api/providers/status'
    | '/api/refresh/nft-data'
    | '/api/refresh/verified-sales'
    | '/api/rwa-market/enrich-sale'
    | '/api/rwa-market/events'
    | '/api/rwa-market/latest-sales'
    | '/api/rwa-market/listed'
    | '/api/rwa-market/stats'
    | '/api/sales/latest'
    | '/api/scan/nft-market-states'
    | '/api/verified-sales/latest'
    | '/api/index/pokemon'
    | '/api/gacha/status/$drawId'
    | '/api/nfts/$assetMint/market-state'
    | '/api/nfts/collections/allowed'
    | '/api/nfts/collections/ingest'
    | '/api/nfts/collections/preview'
    | '/api/sales/market/$market'
    | '/api/sales/provider/$provider'
    | '/api/webhooks/helius/nft-events'
    | '/api/index/pokemon/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  GameRoute: typeof GameRoute
  ApiMarketSalesRoute: typeof ApiMarketSalesRoute
  ApiMarketsRoute: typeof ApiMarketsRouteWithChildren
  ApiNftListRoute: typeof ApiNftListRoute
  ApiNftsRoute: typeof ApiNftsRouteWithChildren
  ApiVerifiedListedRoute: typeof ApiVerifiedListedRoute
  ApiVerifiedSalesRoute: typeof ApiVerifiedSalesRouteWithChildren
  ApiDiscoverNewMintsRoute: typeof ApiDiscoverNewMintsRoute
  ApiGachaAdminRoute: typeof ApiGachaAdminRoute
  ApiGachaConfirmPaymentRoute: typeof ApiGachaConfirmPaymentRoute
  ApiGachaDecideRoute: typeof ApiGachaDecideRoute
  ApiGachaDrawRoute: typeof ApiGachaDrawRoute
  ApiGachaOddsRoute: typeof ApiGachaOddsRoute
  ApiHeliusKeysRoute: typeof ApiHeliusKeysRoute
  ApiProvidersStatusRoute: typeof ApiProvidersStatusRoute
  ApiRefreshNftDataRoute: typeof ApiRefreshNftDataRoute
  ApiRefreshVerifiedSalesRoute: typeof ApiRefreshVerifiedSalesRoute
  ApiRwaMarketEnrichSaleRoute: typeof ApiRwaMarketEnrichSaleRoute
  ApiRwaMarketEventsRoute: typeof ApiRwaMarketEventsRoute
  ApiRwaMarketLatestSalesRoute: typeof ApiRwaMarketLatestSalesRoute
  ApiRwaMarketListedRoute: typeof ApiRwaMarketListedRoute
  ApiRwaMarketStatsRoute: typeof ApiRwaMarketStatsRoute
  ApiSalesLatestRoute: typeof ApiSalesLatestRoute
  ApiScanNftMarketStatesRoute: typeof ApiScanNftMarketStatesRoute
  ApiIndexPokemonRoute: typeof ApiIndexPokemonRouteWithChildren
  ApiGachaStatusDrawIdRoute: typeof ApiGachaStatusDrawIdRoute
  ApiSalesMarketMarketRoute: typeof ApiSalesMarketMarketRoute
  ApiSalesProviderProviderRoute: typeof ApiSalesProviderProviderRoute
  ApiWebhooksHeliusNftEventsRoute: typeof ApiWebhooksHeliusNftEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verified-sales': {
      id: '/api/verified-sales'
      path: '/api/verified-sales'
      fullPath: '/api/verified-sales'
      preLoaderRoute: typeof ApiVerifiedSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verified-listed': {
      id: '/api/verified-listed'
      path: '/api/verified-listed'
      fullPath: '/api/verified-listed'
      preLoaderRoute: typeof ApiVerifiedListedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nfts': {
      id: '/api/nfts'
      path: '/api/nfts'
      fullPath: '/api/nfts'
      preLoaderRoute: typeof ApiNftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nft-list': {
      id: '/api/nft-list'
      path: '/api/nft-list'
      fullPath: '/api/nft-list'
      preLoaderRoute: typeof ApiNftListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-sales': {
      id: '/api/market-sales'
      path: '/api/market-sales'
      fullPath: '/api/market-sales'
      preLoaderRoute: typeof ApiMarketSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/verified-sales': {
      id: '/_app/verified-sales'
      path: '/verified-sales'
      fullPath: '/verified-sales'
      preLoaderRoute: typeof AppVerifiedSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verified-listed': {
      id: '/_app/verified-listed'
      path: '/verified-listed'
      fullPath: '/verified-listed'
      preLoaderRoute: typeof AppVerifiedListedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nft-list': {
      id: '/_app/nft-list'
      path: '/nft-list'
      fullPath: '/nft-list'
      preLoaderRoute: typeof AppNftListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gacha': {
      id: '/_app/gacha'
      path: '/gacha'
      fullPath: '/gacha'
      preLoaderRoute: typeof AppGachaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/control-panel': {
      id: '/_app/control-panel'
      path: '/control-panel'
      fullPath: '/control-panel'
      preLoaderRoute: typeof AppControlPanelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/index/pokemon': {
      id: '/api/index/pokemon'
      path: '/api/index/pokemon'
      fullPath: '/api/index/pokemon'
      preLoaderRoute: typeof ApiIndexPokemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verified-sales/latest': {
      id: '/api/verified-sales/latest'
      path: '/latest'
      fullPath: '/api/verified-sales/latest'
      preLoaderRoute: typeof ApiVerifiedSalesLatestRouteImport
      parentRoute: typeof ApiVerifiedSalesRoute
    }
    '/api/scan/nft-market-states': {
      id: '/api/scan/nft-market-states'
      path: '/api/scan/nft-market-states'
      fullPath: '/api/scan/nft-market-states'
      preLoaderRoute: typeof ApiScanNftMarketStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales/latest': {
      id: '/api/sales/latest'
      path: '/api/sales/latest'
      fullPath: '/api/sales/latest'
      preLoaderRoute: typeof ApiSalesLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rwa-market/stats': {
      id: '/api/rwa-market/stats'
      path: '/api/rwa-market/stats'
      fullPath: '/api/rwa-market/stats'
      preLoaderRoute: typeof ApiRwaMarketStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rwa-market/listed': {
      id: '/api/rwa-market/listed'
      path: '/api/rwa-market/listed'
      fullPath: '/api/rwa-market/listed'
      preLoaderRoute: typeof ApiRwaMarketListedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rwa-market/latest-sales': {
      id: '/api/rwa-market/latest-sales'
      path: '/api/rwa-market/latest-sales'
      fullPath: '/api/rwa-market/latest-sales'
      preLoaderRoute: typeof ApiRwaMarketLatestSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rwa-market/events': {
      id: '/api/rwa-market/events'
      path: '/api/rwa-market/events'
      fullPath: '/api/rwa-market/events'
      preLoaderRoute: typeof ApiRwaMarketEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rwa-market/enrich-sale': {
      id: '/api/rwa-market/enrich-sale'
      path: '/api/rwa-market/enrich-sale'
      fullPath: '/api/rwa-market/enrich-sale'
      preLoaderRoute: typeof ApiRwaMarketEnrichSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refresh/verified-sales': {
      id: '/api/refresh/verified-sales'
      path: '/api/refresh/verified-sales'
      fullPath: '/api/refresh/verified-sales'
      preLoaderRoute: typeof ApiRefreshVerifiedSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refresh/nft-data': {
      id: '/api/refresh/nft-data'
      path: '/api/refresh/nft-data'
      fullPath: '/api/refresh/nft-data'
      preLoaderRoute: typeof ApiRefreshNftDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/status': {
      id: '/api/providers/status'
      path: '/api/providers/status'
      fullPath: '/api/providers/status'
      preLoaderRoute: typeof ApiProvidersStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nfts/untrack': {
      id: '/api/nfts/untrack'
      path: '/untrack'
      fullPath: '/api/nfts/untrack'
      preLoaderRoute: typeof ApiNftsUntrackRouteImport
      parentRoute: typeof ApiNftsRoute
    }
    '/api/nfts/tracked': {
      id: '/api/nfts/tracked'
      path: '/tracked'
      fullPath: '/api/nfts/tracked'
      preLoaderRoute: typeof ApiNftsTrackedRouteImport
      parentRoute: typeof ApiNftsRoute
    }
    '/api/nfts/track': {
      id: '/api/nfts/track'
      path: '/track'
      fullPath: '/api/nfts/track'
      preLoaderRoute: typeof ApiNftsTrackRouteImport
      parentRoute: typeof ApiNftsRoute
    }
    '/api/nfts/status': {
      id: '/api/nfts/status'
      path: '/status'
      fullPath: '/api/nfts/status'
      preLoaderRoute: typeof ApiNftsStatusRouteImport
      parentRoute: typeof ApiNftsRoute
    }
    '/api/nfts/refresh': {
      id: '/api/nfts/refresh'
      path: '/refresh'
      fullPath: '/api/nfts/refresh'
      preLoaderRoute: typeof ApiNftsRefreshRouteImport
      parentRoute: typeof ApiNftsRoute
    }
    '/api/nfts/enrich': {
      id: '/api/nfts/enrich'
      path: '/enrich'
      fullPath: '/api/nfts/enrich'
      preLoaderRoute: typeof ApiNftsEnrichRouteImport
      parentRoute: typeof ApiNftsRoute
    }
    '/api/nfts/$assetMint': {
      id: '/api/nfts/$assetMint'
      path: '/$assetMint'
      fullPath: '/api/nfts/$assetMint'
      preLoaderRoute: typeof ApiNftsAssetMintRouteImport
      parentRoute: typeof ApiNftsRoute
    }
    '/api/markets/state': {
      id: '/api/markets/state'
      path: '/state'
      fullPath: '/api/markets/state'
      preLoaderRoute: typeof ApiMarketsStateRouteImport
      parentRoute: typeof ApiMarketsRoute
    }
    '/api/helius/keys': {
      id: '/api/helius/keys'
      path: '/api/helius/keys'
      fullPath: '/api/helius/keys'
      preLoaderRoute: typeof ApiHeliusKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gacha/odds': {
      id: '/api/gacha/odds'
      path: '/api/gacha/odds'
      fullPath: '/api/gacha/odds'
      preLoaderRoute: typeof ApiGachaOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gacha/draw': {
      id: '/api/gacha/draw'
      path: '/api/gacha/draw'
      fullPath: '/api/gacha/draw'
      preLoaderRoute: typeof ApiGachaDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gacha/decide': {
      id: '/api/gacha/decide'
      path: '/api/gacha/decide'
      fullPath: '/api/gacha/decide'
      preLoaderRoute: typeof ApiGachaDecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gacha/confirm-payment': {
      id: '/api/gacha/confirm-payment'
      path: '/api/gacha/confirm-payment'
      fullPath: '/api/gacha/confirm-payment'
      preLoaderRoute: typeof ApiGachaConfirmPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gacha/admin': {
      id: '/api/gacha/admin'
      path: '/api/gacha/admin'
      fullPath: '/api/gacha/admin'
      preLoaderRoute: typeof ApiGachaAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover/new-mints': {
      id: '/api/discover/new-mints'
      path: '/api/discover/new-mints'
      fullPath: '/api/discover/new-mints'
      preLoaderRoute: typeof ApiDiscoverNewMintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/collections/$slug': {
      id: '/_app/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof AppCollectionsSlugRouteImport
      parentRoute: typeof AppCollectionsRoute
    }
    '/api/index/pokemon/history': {
      id: '/api/index/pokemon/history'
      path: '/history'
      fullPath: '/api/index/pokemon/history'
      preLoaderRoute: typeof ApiIndexPokemonHistoryRouteImport
      parentRoute: typeof ApiIndexPokemonRoute
    }
    '/api/webhooks/helius/nft-events': {
      id: '/api/webhooks/helius/nft-events'
      path: '/api/webhooks/helius/nft-events'
      fullPath: '/api/webhooks/helius/nft-events'
      preLoaderRoute: typeof ApiWebhooksHeliusNftEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales/provider/$provider': {
      id: '/api/sales/provider/$provider'
      path: '/api/sales/provider/$provider'
      fullPath: '/api/sales/provider/$provider'
      preLoaderRoute: typeof ApiSalesProviderProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales/market/$market': {
      id: '/api/sales/market/$market'
      path: '/api/sales/market/$market'
      fullPath: '/api/sales/market/$market'
      preLoaderRoute: typeof ApiSalesMarketMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nfts/collections/preview': {
      id: '/api/nfts/collections/preview'
      path: '/collections/preview'
      fullPath: '/api/nfts/collections/preview'
      preLoaderRoute: typeof ApiNftsCollectionsPreviewRouteImport
      parentRoute: typeof ApiNftsRoute
    }
    '/api/nfts/collections/ingest': {
      id: '/api/nfts/collections/ingest'
      path: '/collections/ingest'
      fullPath: '/api/nfts/collections/ingest'
      preLoaderRoute: typeof ApiNftsCollectionsIngestRouteImport
      parentRoute: typeof ApiNftsRoute
    }
    '/api/nfts/collections/allowed': {
      id: '/api/nfts/collections/allowed'
      path: '/collections/allowed'
      fullPath: '/api/nfts/collections/allowed'
      preLoaderRoute: typeof ApiNftsCollectionsAllowedRouteImport
      parentRoute: typeof ApiNftsRoute
    }
    '/api/nfts/$assetMint/market-state': {
      id: '/api/nfts/$assetMint/market-state'
      path: '/market-state'
      fullPath: '/api/nfts/$assetMint/market-state'
      preLoaderRoute: typeof ApiNftsAssetMintMarketStateRouteImport
      parentRoute: typeof ApiNftsAssetMintRoute
    }
    '/api/gacha/status/$drawId': {
      id: '/api/gacha/status/$drawId'
      path: '/api/gacha/status/$drawId'
      fullPath: '/api/gacha/status/$drawId'
      preLoaderRoute: typeof ApiGachaStatusDrawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCollectionsRouteChildren {
  AppCollectionsSlugRoute: typeof AppCollectionsSlugRoute
}

const AppCollectionsRouteChildren: AppCollectionsRouteChildren = {
  AppCollectionsSlugRoute: AppCollectionsSlugRoute,
}

const AppCollectionsRouteWithChildren = AppCollectionsRoute._addFileChildren(
  AppCollectionsRouteChildren,
)

interface AppRouteChildren {
  AppCollectionsRoute: typeof AppCollectionsRouteWithChildren
  AppControlPanelRoute: typeof AppControlPanelRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGachaRoute: typeof AppGachaRoute
  AppNftListRoute: typeof AppNftListRoute
  AppSalesRoute: typeof AppSalesRoute
  AppVerifiedListedRoute: typeof AppVerifiedListedRoute
  AppVerifiedSalesRoute: typeof AppVerifiedSalesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCollectionsRoute: AppCollectionsRouteWithChildren,
  AppControlPanelRoute: AppControlPanelRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGachaRoute: AppGachaRoute,
  AppNftListRoute: AppNftListRoute,
  AppSalesRoute: AppSalesRoute,
  AppVerifiedListedRoute: AppVerifiedListedRoute,
  AppVerifiedSalesRoute: AppVerifiedSalesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiMarketsRouteChildren {
  ApiMarketsStateRoute: typeof ApiMarketsStateRoute
}

const ApiMarketsRouteChildren: ApiMarketsRouteChildren = {
  ApiMarketsStateRoute: ApiMarketsStateRoute,
}

const ApiMarketsRouteWithChildren = ApiMarketsRoute._addFileChildren(
  ApiMarketsRouteChildren,
)

interface ApiNftsAssetMintRouteChildren {
  ApiNftsAssetMintMarketStateRoute: typeof ApiNftsAssetMintMarketStateRoute
}

const ApiNftsAssetMintRouteChildren: ApiNftsAssetMintRouteChildren = {
  ApiNftsAssetMintMarketStateRoute: ApiNftsAssetMintMarketStateRoute,
}

const ApiNftsAssetMintRouteWithChildren =
  ApiNftsAssetMintRoute._addFileChildren(ApiNftsAssetMintRouteChildren)

interface ApiNftsRouteChildren {
  ApiNftsAssetMintRoute: typeof ApiNftsAssetMintRouteWithChildren
  ApiNftsEnrichRoute: typeof ApiNftsEnrichRoute
  ApiNftsRefreshRoute: typeof ApiNftsRefreshRoute
  ApiNftsStatusRoute: typeof ApiNftsStatusRoute
  ApiNftsTrackRoute: typeof ApiNftsTrackRoute
  ApiNftsTrackedRoute: typeof ApiNftsTrackedRoute
  ApiNftsUntrackRoute: typeof ApiNftsUntrackRoute
  ApiNftsCollectionsAllowedRoute: typeof ApiNftsCollectionsAllowedRoute
  ApiNftsCollectionsIngestRoute: typeof ApiNftsCollectionsIngestRoute
  ApiNftsCollectionsPreviewRoute: typeof ApiNftsCollectionsPreviewRoute
}

const ApiNftsRouteChildren: ApiNftsRouteChildren = {
  ApiNftsAssetMintRoute: ApiNftsAssetMintRouteWithChildren,
  ApiNftsEnrichRoute: ApiNftsEnrichRoute,
  ApiNftsRefreshRoute: ApiNftsRefreshRoute,
  ApiNftsStatusRoute: ApiNftsStatusRoute,
  ApiNftsTrackRoute: ApiNftsTrackRoute,
  ApiNftsTrackedRoute: ApiNftsTrackedRoute,
  ApiNftsUntrackRoute: ApiNftsUntrackRoute,
  ApiNftsCollectionsAllowedRoute: ApiNftsCollectionsAllowedRoute,
  ApiNftsCollectionsIngestRoute: ApiNftsCollectionsIngestRoute,
  ApiNftsCollectionsPreviewRoute: ApiNftsCollectionsPreviewRoute,
}

const ApiNftsRouteWithChildren =
  ApiNftsRoute._addFileChildren(ApiNftsRouteChildren)

interface ApiVerifiedSalesRouteChildren {
  ApiVerifiedSalesLatestRoute: typeof ApiVerifiedSalesLatestRoute
}

const ApiVerifiedSalesRouteChildren: ApiVerifiedSalesRouteChildren = {
  ApiVerifiedSalesLatestRoute: ApiVerifiedSalesLatestRoute,
}

const ApiVerifiedSalesRouteWithChildren =
  ApiVerifiedSalesRoute._addFileChildren(ApiVerifiedSalesRouteChildren)

interface ApiIndexPokemonRouteChildren {
  ApiIndexPokemonHistoryRoute: typeof ApiIndexPokemonHistoryRoute
}

const ApiIndexPokemonRouteChildren: ApiIndexPokemonRouteChildren = {
  ApiIndexPokemonHistoryRoute: ApiIndexPokemonHistoryRoute,
}

const ApiIndexPokemonRouteWithChildren = ApiIndexPokemonRoute._addFileChildren(
  ApiIndexPokemonRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GameRoute: GameRoute,
  ApiMarketSalesRoute: ApiMarketSalesRoute,
  ApiMarketsRoute: ApiMarketsRouteWithChildren,
  ApiNftListRoute: ApiNftListRoute,
  ApiNftsRoute: ApiNftsRouteWithChildren,
  ApiVerifiedListedRoute: ApiVerifiedListedRoute,
  ApiVerifiedSalesRoute: ApiVerifiedSalesRouteWithChildren,
  ApiDiscoverNewMintsRoute: ApiDiscoverNewMintsRoute,
  ApiGachaAdminRoute: ApiGachaAdminRoute,
  ApiGachaConfirmPaymentRoute: ApiGachaConfirmPaymentRoute,
  ApiGachaDecideRoute: ApiGachaDecideRoute,
  ApiGachaDrawRoute: ApiGachaDrawRoute,
  ApiGachaOddsRoute: ApiGachaOddsRoute,
  ApiHeliusKeysRoute: ApiHeliusKeysRoute,
  ApiProvidersStatusRoute: ApiProvidersStatusRoute,
  ApiRefreshNftDataRoute: ApiRefreshNftDataRoute,
  ApiRefreshVerifiedSalesRoute: ApiRefreshVerifiedSalesRoute,
  ApiRwaMarketEnrichSaleRoute: ApiRwaMarketEnrichSaleRoute,
  ApiRwaMarketEventsRoute: ApiRwaMarketEventsRoute,
  ApiRwaMarketLatestSalesRoute: ApiRwaMarketLatestSalesRoute,
  ApiRwaMarketListedRoute: ApiRwaMarketListedRoute,
  ApiRwaMarketStatsRoute: ApiRwaMarketStatsRoute,
  ApiSalesLatestRoute: ApiSalesLatestRoute,
  ApiScanNftMarketStatesRoute: ApiScanNftMarketStatesRoute,
  ApiIndexPokemonRoute: ApiIndexPokemonRouteWithChildren,
  ApiGachaStatusDrawIdRoute: ApiGachaStatusDrawIdRoute,
  ApiSalesMarketMarketRoute: ApiSalesMarketMarketRoute,
  ApiSalesProviderProviderRoute: ApiSalesProviderProviderRoute,
  ApiWebhooksHeliusNftEventsRoute: ApiWebhooksHeliusNftEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
